ChEBUTEApps/ChEBUTEApps/Controllers/StudentCornerController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ChEBUTEApps.BBL;
using ChEBUTEApps.Models;

namespace ChEBUTEApps.Controllers
{
    public class StudentCornerController : Controller
    {
        BatchManager aBatchManager=new BatchManager();



        // GET: StudentCorner
        public ActionResult Info()
        {
            return View();
        }

        public ActionResult File()
        {
           // ViewBag.BatchList=aBatchManager.GetBatchList();
            return View();

        }

        [HttpPost]
        public ActionResult File(Upload model)
        {
            //FireBase Connect
           // ViewBag.BatchList = aBatchManager.GetBatchList();
            ViewBag.Message = "Under Processing...";

            return View();
        }









        public ActionResult QuestionBank()
        {
            return View();
        }

        public ActionResult Library()
        {
            return View();
        }

        public ActionResult ModifyUpload()
        {
            return View();
        }
        [HttpPost]
        public ActionResult ModifyUpload(NewUpload aNewUpload)
        {
            //FireBase Connect here

            ViewBag.Message = "Under Processing...";
            return View();
        }

    }

}

ChEBUTEApps/ChEBUTEApps/Views/StudentCorner/File.cshtml
@using ChEBUTEApps.Models
@model ChEBUTEApps.Models.Upload

@{
    ViewBag.Title = "Upload's";
    Layout = "~/Views/Shared/_Layout.cshtml";
    List<Batch> allBatch = ViewBag.BatchList;
}

@using (Html.BeginForm("File", "StudentCorner", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <fieldset>
        <legend style="padding-top: 35px;">Custom Files Sender DashBoard...</legend>
        <div class="col-md-12">
            <div style="background-color: orange !important; height: 33px;" class="col-md-3">
                <div style="float: left;">
                    <div style="float: left;">
                        @Html.Label("Batch", new { @style = "color: whitesmoke!important; padding-left: 10px; padding-top: 7px;" })
                    </div>
                    <div style="float: left; margin-left: 30px;">
                        <select name="ID" id="Name" class="form-control">
                            <option value="">...Select Batch...</option>
                            <option value="">Batch Name-1</option>
                            <option value="">Batch Name-2</option>
                            <option value="">Batch Name-3</option>



                            @*@foreach (var aBatch in allBatch)
                            {
                                <option value="@aBatch.ID">@aBatch.Name</option>
                            }*@
                        </select>
                    </div>
                </div>
            </div>
            <div class="col-md-9" style="background-color: ; height: 33px;">
                <h4 style="text-align: left;">OR</h4>
            </div>
        </div>
        <div class="col-md-12">
            <br />
        </div>
        <div class="col-md-12">
            <div style="background-color: orange !important; height: 33px;" class="col-md-7">
                <div style="float: left;">
                    <div style="float: left;">
                        @Html.Label("Batch", new { @style = "color: whitesmoke!important; padding-left: 10px; padding-top: 7px;" })
                    </div>
                    <div style="float: left; margin-left: 30px;">
                        <select name="ID" id="Name" class="form-control">
                            <option value="">...Select Batch...</option>
                            <option value="">Batch Name-1</option>
                            <option value="">Batch Name-2</option>
                            <option value="">Batch Name-3</option>
                            @*@foreach (var aBatch in allBatch)
                            {
                                <option value="@aBatch.ID">@aBatch.Name</option>
                            }*@
                        </select>
                    </div>
                </div>
                <div style="float: left;" class="col-md-offset-1">
                    <div style="float: left">
                        @Html.LabelFor(x => x.SpecificID, new { @style = "color: whitesmoke!important; padding-left: 10px; padding-top: 7px;" })
                    </div>
                    <div style="float: left; margin-left: 30px;">
                        @Html.TextBoxFor(x => x.SpecificID, new { type = "text", @class = "form-control", @placeholder = "Specific ID" })
                    </div>
                </div>
            </div>
            <div class="col-md-5">
                <h4 style="text-align: left">OR</h4>

            </div>
        </div>
        <div class="col-md-12">
            <br />
        </div>
        <div class="col-md-12">
            <div style="background-color: orange !important; height: 33px;" class="col-md-12">
                <div style="float: left;">
                    <div style="float: left;">
                        @Html.Label("Batch", new { @style = "color: whitesmoke!important; padding-left: 10px; padding-top: 7px;" })
                    </div>
                    <div style="float: left; margin-left: 30px;">
                        <select name="ID" id="Name" class="form-control">
                            <option value="">...Select Batch...</option>
                            <option value="">Batch Name-1</option>
                            <option value="">Batch Name-2</option>
                            <option value="">Batch Name-3</option>
                            @*@foreach (var aBatch in allBatch)
                            {
                                <option value="@aBatch.ID">@aBatch.Name</option>
                            }*@
                        </select>
                    </div>
                </div>
                <div style="float: left;" class="col-md-offset-1">
                    <div style="float: left">
                        @Html.LabelFor(x => x.StartID, new { @style = "color: whitesmoke!important; padding-left: 10px; padding-top: 7px;" })
                    </div>
                    <div style="float: left; margin-left: 30px;">
                        @Html.TextBoxFor(x => x.StartID, new { type = "text", @class = "form-control", @placeholder = "Start ID" })
                    </div>
                </div>
                <div style="float: left;" class="col-md-offset-1">
                    <div style="float: left">
                        @Html.LabelFor(x => x.EndingID, new { @style = "color: whitesmoke!important; padding-left: 10px; padding-top: 7px;" })
                    </div>
                    <div style="float: left; margin-left: 30px;">
                        @Html.TextBoxFor(x => x.EndingID, new { type = "text", @class = "form-control", @placeholder = "Ending ID" })
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-12">
            <br />
        </div>
        <div class="col-md-12">
            @Html.Label("Select Files...", new { @style = "color: whitesmoke!important; padding-left: 10px; padding-top: 7px;" })
            @Html.TextBoxFor(x => x.Files, new { type = "file" })
            @Html.ValidationMessageFor(x => x.Files,"", new { @style = "color: red!important;"})
            <br />
            <button type="submit" class="btn btn-warning">Upload</button>
            @if (@ViewBag.Message != null)
            {
                <h3 style="color: red;">
                    @ViewBag.Message
                </h3>

            }
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
           
        </div>

    </fieldset>
}


@section BodyScripts
{
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script>



    </script>
}

ChEBUTEApps/ChEBUTEApps/Views/StudentCorner/Info.cshtml
@model dynamic

@{
    ViewBag.Title = "Info";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br /><br /><br /><br />
<h3 style="text-align: center">Batch Information Content Here...</h3>
<br /><br /><br /><br /><br /><br /><br />

ChEBUTEApps/ChEBUTEApps/Views/StudentCorner/Library.cshtml
@model dynamic

@{
    ViewBag.Title = "Library";
    Layout = "~/Views/Shared/_Layout.cshtml";

}
<br /><br /><br /><br />
<h3 style="text-align: center">Library Content Here...</h3>
<br /><br /><br /><br /><br /><br /><br />

ChEBUTEApps/ChEBUTEApps/Views/StudentCorner/ModifyUpload.cshtml
@model ChEBUTEApps.Models.NewUpload

@{
    ViewBag.Title = "ModifyUpload";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Upload</h3>
<div class="col-md-9 col-md-offset-3">

@using (Html.BeginForm("ModifyUpload", "StudentCorner", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Team, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Team, new { htmlAttributes = new { @class = "form-control", @placeholder = "Team Name Here..." } })
                @Html.ValidationMessageFor(model => model.Team, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Section, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Section, new { htmlAttributes = new { @class = "form-control", @placeholder = "Section Name Here..." } })
                @Html.ValidationMessageFor(model => model.Section, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CourseName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CourseName, new { htmlAttributes = new { @class = "form-control", @placeholder = "Course Name Here..." } })
                @Html.ValidationMessageFor(model => model.CourseName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ExamName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ExamName, new { htmlAttributes = new { @class = "form-control", @placeholder = "Exam Name Here..." } })
                @Html.ValidationMessageFor(model => model.ExamName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TotalMark, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TotalMark, new { htmlAttributes = new { @class = "form-control", @placeholder = "Total Mark Here..." } })
                @Html.ValidationMessageFor(model => model.TotalMark, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-warning" />
            </div>
        </div>
        @if (@ViewBag.Message != null)
        {
            <h3 style="color: red;">
                @ViewBag.Message
            </h3>

        }
    </div>
}

    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ChEBUTEApps/ChEBUTEApps/Views/StudentCorner/QuestionBank.cshtml
@model dynamic

@{
  ViewBag.Title = "Question Bank";
  Layout = "~/Views/Shared/_Layout.cshtml";
}
<br /><br /><br /><br />
<h3 style="text-align: center">Question Bank Content Here...</h3>
<br /><br /><br /><br /><br /><br /><br />