GoContributeMe/GoContributeMe/Models/Model/Campaign.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace GoContributeMe.Models.Model
{
    public class Campaign
    {
        public int CampaignID { get; set; }
        [Required(ErrorMessage = "Field can't be empty")]

        public string Tittle { get; set; }
        [Required(ErrorMessage = "Field can't be empty")]
        [Display(Name = "Category Type")]
        public int CategoryID { get; set; }
        [Display(Name = "Category Type")]
        public Category Category { get; set; }


        [Required(ErrorMessage = "Field can't be empty")]
        public string Descriptions { get; set; }
        [Required(ErrorMessage = "Field can't be empty")]
        [Display(Name = "Contribution Type")]
        public int ContributionID { get; set; }
        [Display(Name = "Contribution Type")]
        public Contribution Contribution { get; set; }
        //public string Image { get; set; }
        [Required(ErrorMessage = "Field can't be empty")]
        [Display(Name = "Name")]
        public string RecipientName { get; set; }

        [Required(ErrorMessage = "Field can't be empty")]
        [Display(Name = "NID")]
        public string RecipientNID { get; set; }
        [Required(ErrorMessage = "Field can't be empty")]
        [RegularExpression(@"[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?", ErrorMessage = "Please provide valid email")]

        public string Email { get; set; }
        [Required(ErrorMessage = "Field can't be empty")]
        [Display(Name = "Mobile Number")]
        public string MobileNo { get; set; }
        [Required(ErrorMessage = "Field can't be empty")]
        [Display(Name = "Target Amount")]
        public string TargetAmount { get; set; }
        [Required(ErrorMessage = "Field can't be empty")]
        [Display(Name = "Campaign Closing Date")]
        public DateTime CampaignClosingDate { get; set; }
        //[DisplayName("I accept terms and conditions")]
        //[RegularExpression("True", ErrorMessage = "You must accept the terms and conditions")]
        [Required]
        [NotMapped]
        public bool TermsConditions { get; set; }
    }
}

GoContributeMe/GoContributeMe/Controllers/CampaignsController.cs
using GoContributeMe.Context;
using GoContributeMe.Models.Model;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace GoContributeMe.Controllers
{
    public class CampaignsController : Controller
    {
        private GoContributeMeDB db = new GoContributeMeDB();


        // GET: Campaigns
        public ActionResult Index()
        {
            var campaign = db.Campaign.Include(c => c.Category).Include(c => c.Contribution);
            return View(campaign.ToList());
        }

        // GET: Campaigns/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Campaign campaign = db.Campaign.Find(id);
            if (campaign == null)
            {
                return HttpNotFound();
            }
            return View(campaign);
        }

        // GET: Campaigns/Create

        public ActionResult Create()
        {
            ViewBag.CategoryID = new SelectList(db.Category, "CategoryID", "Name");
            ViewBag.ContributionID = new SelectList(db.Contribution, "ContributionID", "Name");
            return View();
        }

        // POST: Campaigns/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Campaign campaign)
        {
            TempData.Clear();
            TempData["aCampaign"] = campaign;
            return RedirectToAction("FundRecipient");
        }

        public ActionResult FundRecipient()
        {

            return View();
        }
        [HttpPost]
        public ActionResult FundRecipient(Campaign aCampaigna)
        {
            Campaign aCampaignCreate = (Campaign)TempData["aCampaign"];
            if (aCampaigna.RecipientName != null)
            {
                aCampaigna.Tittle = aCampaignCreate.Tittle;
                aCampaigna.CategoryID = aCampaignCreate.CategoryID;
                aCampaigna.ContributionID = aCampaignCreate.ContributionID;
                aCampaigna.Descriptions = aCampaignCreate.Descriptions;

                db.Campaign.Add(aCampaigna);
                db.SaveChanges();
                ModelState.Clear();
                return RedirectToAction("Account", "User");
            }

            return HttpNotFound();
        }

        // GET: Campaigns/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Campaign campaign = db.Campaign.Find(id);
            if (campaign == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryID = new SelectList(db.Category, "CategoryID", "Name", campaign.CategoryID);
            ViewBag.ContributionID = new SelectList(db.Contribution, "ContributionID", "Name", campaign.ContributionID);
            return View(campaign);
        }

        // POST: Campaigns/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CampaignID,Tittle,CategoryID,Descriptions,ContributionID,RecipientFirstName,RecipientLastName,RecipientNID,Email,MobileNo,TargetAmount,CampaignClosingDate")] Campaign campaign)
        {
            if (ModelState.IsValid)
            {
                db.Entry(campaign).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CategoryID = new SelectList(db.Category, "CategoryID", "Name", campaign.CategoryID);
            ViewBag.ContributionID = new SelectList(db.Contribution, "ContributionID", "Name", campaign.ContributionID);
            return View(campaign);
        }

        // GET: Campaigns/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Campaign campaign = db.Campaign.Find(id);
            if (campaign == null)
            {
                return HttpNotFound();
            }
            return View(campaign);
        }

        // POST: Campaigns/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Campaign campaign = db.Campaign.Find(id);
            db.Campaign.Remove(campaign);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GoContributeMe/GoContributeMe/Views/Campaigns/Create.cshtml
@model GoContributeMe.Models.Model.Campaign

@{
    ViewBag.Title = "Create Campaign";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}
@section BodyNeededCSS
{
    <style type="text/css">
       
        .form-style-3 textarea {
                
                height: 100px;
            }
    </style>
}

<div class="col-md-12 jumbotron">
    @using (Html.BeginForm("Create", "Campaigns", FormMethod.Post, new { id = " ", @class = "form-group" }))
    {
        @Html.AntiForgeryToken()
        @*<h2 style="text-align: center;">Create your won Fundrising Campaign</h2>*@
        <br />
        <div class="col-md-offset-2 col-md-10 col-lg-offset-2 col-lg-10">
            <div class="form-style-3">
                <fieldset>
                    <legend>Create your won Fundrising Campaign</legend>
                    <div class="form-group col-md-12 col-lg-12">
                        @Html.LabelFor(model => model.Tittle, htmlAttributes: new { @class = "control-label col-md-3 col-lg-3" })
                        <div class="col-md-6 col-lg-6">
                            @Html.EditorFor(model => model.Tittle, new {htmlAttributes = new {@class = "form-control", @placeholder = "Tittle"}})
                        </div>
                        @Html.ValidationMessageFor(model => model.Tittle, "", new { @class = "text-danger" })


                    </div>

                    <div class="form-group col-md-12 col-lg-12">
                        @Html.LabelFor(model => model.CategoryID, "Category Type", htmlAttributes: new { @class = "control-label col-md-3 col-lg-3" })
                        <div class="col-md-6 col-lg-6">
                            @Html.DropDownListFor(a => a.CategoryID, new SelectList(ViewBag.CategoryID, "Value", "Text"), "---Select Your Category---", new {@class = "form-control"})
                        </div>
                        @Html.ValidationMessageFor(model => model.CategoryID, "", new { @class = "text-danger" })


                    </div>

                    <div class="form-group col-md-12 col-lg-12">

                        @Html.LabelFor(model => model.Descriptions, htmlAttributes: new { @class = "control-label col-md-3 col-lg-3" })
                        <div class="col-md-6 col-lg-6">
                            @Html.TextAreaFor(x => x.Descriptions, new {@class = "form-control", @placeholder = "Descriptions"})
                        </div>
                        @Html.ValidationMessageFor(a => a.Descriptions)




                    </div>
                    <div class="form-group col-md-12 col-lg-12">
                        @Html.LabelFor(model => model.ContributionID, "Contribution Type", htmlAttributes: new {@class = "control-label col-md-3 col-lg-3"})
                        <div class="col-md-6 col-lg-6">
                            @Html.DropDownListFor(a => a.ContributionID, new SelectList(ViewBag.ContributionID, "Value", "Text"), "---Select Your Contribution---", new {@class = "form-control"})
                        </div>
                        @Html.ValidationMessageFor(model => model.ContributionID, "", new {@class = "text-danger"})

                    </div>
                    <div class="form-group col-md-12 col-lg-12">
                        <div class="control-label col-md-3 col-lg-3">
                            <label for="female">Cover Image</label>
                        </div>
                      

                        <div class="col-md-6 col-lg-6">
                            <input type="file" name="ImageData" id="ImageData" onchange="fileCheck(this);"/>
                        </div>


                    </div>
                    <div class="form-group col-md-offset-3 col-md-9">
                        <button class="btn btn-success" type="submit" style="margin-top: 8px !important;">
                            Next<span class="fa fa-arrow-right fa-x"></span>
                        </button>
                    </div>
                  
                </fieldset>



              
            </div>

        </div>
    }
</div>

GoContributeMe/GoContributeMe/Views/Campaigns/FundRecipient.cshtml
@model GoContributeMe.Models.Model.Campaign

@{
    ViewBag.Title = "Recipient";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<div class="col-md-12 jumbotron">
    @using (Html.BeginForm("FundRecipient", "Campaigns", FormMethod.Post, new { id = " ", @class = "form-group" }))
    {
        @Html.AntiForgeryToken()
        @*<h2 style="text-align: center;">Create your won Fundrising Campaign</h2>*@
        <br />
        <div class="col-md-offset-2 col-md-10 col-lg-offset-2 col-lg-10">
            <div class="form-style-3">
                <fieldset>
                    <legend>Fund Recipient Information</legend>
                    <div class="form-group col-md-12 col-lg-12">
                        @Html.LabelFor(model => model.RecipientName, htmlAttributes: new { @class = "control-label col-md-3 col-lg-3" })
                        <div class="col-md-6 col-lg-6">
                            @Html.EditorFor(model => model.RecipientName, new { htmlAttributes = new { @class = "form-control", @placeholder = "Recipient Name" } })
                        </div>
                        @Html.ValidationMessageFor(model => model.RecipientName, "", new { @class = "text-danger" })


                    </div>
                    <div class="form-group col-md-12 col-lg-12">
                        @Html.LabelFor(model => model.RecipientNID, htmlAttributes: new { @class = "control-label col-md-3 col-lg-3" })
                        <div class="col-md-6 col-lg-6">
                            @Html.EditorFor(model => model.RecipientNID, new { htmlAttributes = new { @class = "form-control", @placeholder = "Recipient NID" } })
                        </div>
                        @Html.ValidationMessageFor(model => model.RecipientNID, "", new { @class = "text-danger" })


                    </div>

                    <div class="form-group col-md-12 col-lg-12">
                        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-3 col-lg-3" })
                        <div class="col-md-6 col-lg-6">
                            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", @placeholder = "Recipient Email" } })
                        </div>
                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })


                    </div>

                    <div class="form-group col-md-12 col-lg-12">
                        @Html.LabelFor(model => model.MobileNo, htmlAttributes: new { @class = "control-label col-md-3 col-lg-3" })
                        <div class="col-md-6 col-lg-6">
                            @Html.EditorFor(model => model.MobileNo, new { htmlAttributes = new { @class = "form-control", @placeholder = "Recipient Mobile Number" } })
                        </div>
                        @Html.ValidationMessageFor(model => model.MobileNo, "", new { @class = "text-danger" })


                    </div>

                    <div class="form-group col-md-12 col-lg-12">
                        @Html.LabelFor(model => model.TargetAmount, htmlAttributes: new { @class = "control-label col-md-3 col-lg-3" })
                        <div class="col-md-6 col-lg-6">
                            @Html.EditorFor(model => model.TargetAmount, new { htmlAttributes = new { @class = "form-control", @placeholder = "Recipient Amount" } })
                        </div>
                        @Html.ValidationMessageFor(model => model.TargetAmount, "", new { @class = "text-danger" })


                    </div>

                    <div class="form-group col-md-12 col-lg-12">
                        @Html.LabelFor(model => model.CampaignClosingDate, htmlAttributes: new {@class = "control-label col-md-3 col-lg-3"})
                        <div class="col-md-6 col-lg-6">
                            @Html.EditorFor(model => model.CampaignClosingDate, new {htmlAttributes = new {@class = "form-control", @placeholder = "Recipient Closing Date"}})
                        </div>
                        @Html.ValidationMessageFor(model => model.CampaignClosingDate, "", new {@class = "text-danger"})


                    </div>
                    <div class="form-group col-md-12 col-lg-12">
                        <div class="col-md-offset-3 col-md-6 col-lg-offset-3 col-lg-6">
                            <div class="col-xs-3 col-sm-1 col-md-1 col-lg-2">
                                @Html.CheckBoxFor(m => m.TermsConditions, new { @checked = "checked" })
                            </div>

                            <div class="col-xs-9 col-sm-11 col-md-11 col-lg-10">
                                <p style="font-size: 12px;">I agree to the Terms and Conditions </p>
                                @Html.ValidationMessageFor(model => model.TermsConditions, "", new { @class = "text-danger" })


                            </div>

                        </div>
                    </div>

                    <div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
                        <div class="col-xs-12 col-sm-12 col-md-offset-2 col-md-10 col-lg-offset-2 col-lg-10">
                            <div class="col-xs-6 col-sm-4 col-md-offset-1 col-md-4">
                                @*<button class="btn btn-warning" type="submit" style="margin-top: 8px !important;">
                                        <span class="fa fa-arrow-left fa-x"></span>Back
                                    </button>*@

                                @Html.ActionLink("Back", "Create")
                            </div>
                            <div class="col-xs-6 col-sm-8 col-md-7">
                                <button class="btn btn-success" type="submit" style="margin-top: 8px !important;">
                                    Submit<span class="fa fa-paper-plane"></span>
                                </button>
                            </div>

                        </div>

                    </div>


                </fieldset>
            </div>
        </div>
    }
</div>